### ISSUE TITLE
Do I really need to install other things from source?

### ISSUE THREAD

**Issue by Ch0ronomato** [sassanh/qnvim#32] opened 2022-09-22 22:55 UTC
If I wanted to just download qt creator, and `brew install nvim-qt`, how would I do that?

**Comment by sassanh** [comment] 2022-09-24 17:24
Sorry, this project is not maintained for ~2 years. I tried to update it with latest versions of Noevim and Qt Creator but it is pending this issue in neovim-qt: https://github.com/equalsraf/neovim-qt/issues/839
The problem is Qt Creator is migrated to Qt 6 for a long time and as far as I know it's not possible to install Qt 5 extensions for it.

**Comment by sassanh** [comment] 2022-12-09 07:08
So things have improved since then. Thanks to Mikhail’s contributions it is now much easier to install the plugin, you can either directly download the plugin for your distribution from releases section or build it yourself with few simple commands (now it fetches its dependencies itself) so I close this issue. Please feel free to reopen it if you think your concerns are not addressed yet.

**Closed by sassanh** 2022-12-09 07:08 UTC
